export const mockProfitBalanceData = [
  {
    _id: "pb1",
    partnerName: "Rafsan Chowdhury",
    partnerDesignation: "Managing Director",
    totalProfitAmount: 15000,
    lastProfitWithdrawalAmount: 15000,
    currentProfitBalance: 12000,
  },
  {
    _id: "pb2",
    partnerName: "Tania Akter",
    partnerDesignation: "Finance Lead",
    totalProfitAmount: 10000,
    lastProfitWithdrawalAmount: 1000,
    currentProfitBalance: 9000,
  },
  {
    _id: "pb3",
    partnerName: "Zahid Hasan",
    partnerDesignation: "Operations Manager",
    totalProfitAmount: 8000,
    lastProfitWithdrawalAmount: 3000,
    currentProfitBalance: 5000,
  },
  {
    _id: "pb4",
    partnerName: "Lamia Rahman",
    partnerDesignation: "Marketing Executive",
    totalProfitAmount: 7000,
    lastProfitWithdrawalAmount: 3000,
    currentProfitBalance: 4000,
  },
  {
    _id: "pb5",
    partnerName: "Fahim Ahmed",
    partnerDesignation: "Product Owner",
    totalProfitAmount: 12000,
    lastProfitWithdrawalAmount: 2000,
    currentProfitBalance: 10000,
  },
  {
    _id: "pb6",
    partnerName: "Nusrat Jahan",
    partnerDesignation: "HR Specialist",
    totalProfitAmount: 5000,
    lastProfitWithdrawalAmount: 3000,
    currentProfitBalance: 2000,
  },
  {
    _id: "pb7",
    partnerName: "Tanvir Hossain",
    partnerDesignation: "IT Consultant",
    totalProfitAmount: 6000,
    lastProfitWithdrawalAmount: 3000,
    currentProfitBalance: 3000,
  },
  {
    _id: "pb8",
    partnerName: "Shamima Nasrin",
    partnerDesignation: "Sales Coordinator",
    totalProfitAmount: 4000,
    lastProfitWithdrawalAmount: 3000,
    currentProfitBalance: 1000,
  },
  {
    _id: "pb9",
    partnerName: "Rakibul Islam",
    partnerDesignation: "Support Engineer",
    totalProfitAmount: 3500,
    lastProfitWithdrawalAmount: 2000,
    currentProfitBalance: 1500,
  },
  {
    _id: "pb10",
    partnerName: "Naimur Rahman",
    partnerDesignation: "Business Analyst",
    totalProfitAmount: 9500,
    lastProfitWithdrawalAmount: 1000,
    currentProfitBalance: 8500,
  },
  {
    _id: "pb11",
    partnerName: "Shuvo Das",
    partnerDesignation: "UX Designer",
    totalProfitAmount: 3000,
    lastProfitWithdrawalAmount: 1500,
    currentProfitBalance: 1500,
  },
  {
    _id: "pb12",
    partnerName: "Mehzabin Karim",
    partnerDesignation: "Legal Advisor",
    totalProfitAmount: 11000,
    lastProfitWithdrawalAmount: 5000,
    currentProfitBalance: 6000,
  },
];
