export const mockProfitBalanceData = [
  {
    _id: "pb1",
    partnerName: "Rafsan Chowdhury",
    partnerDesignation: "Managing Director",
    profitAmount: 15000,
    profitBalance: 12000,
  },
  {
    _id: "pb2",
    partnerName: "Tania Akter",
    partnerDesignation: "Finance Lead",
    profitAmount: 10000,
    profitBalance: 9000,
  },
  {
    _id: "pb3",
    partnerName: "Zahid Hasan",
    partnerDesignation: "Operations Manager",
    profitAmount: 8000,
    profitBalance: 5000,
  },
  {
    _id: "pb4",
    partnerName: "Lamia Rahman",
    partnerDesignation: "Marketing Executive",
    profitAmount: 7000,
    profitBalance: 4000,
  },
  {
    _id: "pb5",
    partnerName: "Fahim Ahmed",
    partnerDesignation: "Product Owner",
    profitAmount: 12000,
    profitBalance: 10000,
  },
  {
    _id: "pb6",
    partnerName: "Nusrat Jahan",
    partnerDesignation: "HR Specialist",
    profitAmount: 5000,
    profitBalance: 2000,
  },
  {
    _id: "pb7",
    partnerName: "Tanvir Hossain",
    partnerDesignation: "IT Consultant",
    profitAmount: 6000,
    profitBalance: 3000,
  },
  {
    _id: "pb8",
    partnerName: "Shamima Nasrin",
    partnerDesignation: "Sales Coordinator",
    profitAmount: 4000,
    profitBalance: 1000,
  },
  {
    _id: "pb9",
    partnerName: "Rakibul Islam",
    partnerDesignation: "Support Engineer",
    profitAmount: 3500,
    profitBalance: 1500,
  },
  {
    _id: "pb10",
    partnerName: "Naimur Rahman",
    partnerDesignation: "Business Analyst",
    profitAmount: 9500,
    profitBalance: 8500,
  },
  {
    _id: "pb11",
    partnerName: "Shuvo Das",
    partnerDesignation: "UX Designer",
    profitAmount: 3000,
    profitBalance: 1500,
  },
  {
    _id: "pb12",
    partnerName: "Mehzabin Karim",
    partnerDesignation: "Legal Advisor",
    profitAmount: 11000,
    profitBalance: 6000,
  },
];
