import { ISupplier } from "@/types";

export const mockSuppliers: ISupplier[] = [
  {
    _id: "1",
    name: "Arctic Clothing Co.",
    address: "123 Frost Lane, Dhaka",
    phoneNumber: "+8801723456789",
    email: "sales@arcticclothing.com",
    logo: "https://example.com/logos/arctic.png",
  },
  {
    _id: "2",
    name: "StyleMan Garments",
    address: "99 Fashion St, Chittagong",
    phoneNumber: "+8801787654321",
    email: "contact@styleman.com",
    logo: "https://example.com/logos/styleman.png",
  },
  {
    _id: "3",
    name: "TeeHub Ltd.",
    address: "Gulshan 1, Dhaka",
    phoneNumber: "+8801999999999",
    email: "support@teehub.com",
    logo: "https://example.com/logos/teehub.png",
  },
  {
    _id: "4",
    name: "RainSafe Ltd.",
    address: "34 Umbrella Rd, Sylhet",
    phoneNumber: "+8801555555555",
    email: "order@rainsafe.com",
    logo: "https://example.com/logos/rainsafe.png",
  },
  {
    _id: "5",
    name: "Denim World",
    address: "West Lane, Dhaka",
    phoneNumber: "+8801888888888",
    email: "denim@denimworld.com",
    logo: "https://example.com/logos/denimworld.png",
  },
  {
    _id: "6",
    name: "MiniWear BD",
    address: "Banani, Dhaka",
    phoneNumber: "+8801777777777",
    email: "info@miniwear.com",
    logo: "https://example.com/logos/miniwear.png",
  },
  {
    _id: "7",
    name: "WalkOn Footwear",
    address: "Dhanmondi, Dhaka",
    phoneNumber: "+8801765432109",
    email: "sales@walkon.com",
    logo: "https://example.com/logos/walkon.png",
  },
  {
    _id: "8",
    name: "Ethnic Vogue",
    address: "Mirpur DOHS, Dhaka",
    phoneNumber: "+8801999888777",
    email: "orders@ethnicvogue.com",
    logo: "https://example.com/logos/ethnicvogue.png",
  },
  {
    _id: "9",
    name: "FitNation",
    address: "GEC Circle, Chittagong",
    phoneNumber: "+8801555123123",
    email: "fit@fitnation.com",
    logo: "https://example.com/logos/fitnation.png",
  },
  {
    _id: "10",
    name: "Heritage Drapes",
    address: "New Market, Dhaka",
    phoneNumber: "+8801345678910",
    email: "hello@heritagedrapes.com",
    logo: "https://example.com/logos/heritagedrapes.png",
  },
];
